---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  name: metallb-operator
  channel: "4.9"
  source: qe-app-registry 
  sourceNamespace: openshift-marketplace

